coalign by solar rotation burn complete
sunpy/sunkit-image pull request #206
Opened 2024-06-04 19:41 UTC by Deus1704

## PR Description

Following our discussion on the removal of the methods `calculate_solar_rotate_shift` and `mapsequence_coalign_by_rotation`, this PR removes them along with removal of the example gallery and the unit tests.

2024-06-19 16:12 UTC, nabobalis approved these changes

2024-06-23 22:19 UTC, wtbarnes commented
The doc build fail is real. It looks like there are still a few references to the removed functions somewhere in the docs. I'm not sure what's going on with the online build.

2024-06-23 22:21 UTC, wtbarnes requested changes
As noted above, the doc build failure still needs fixing.

2024-06-23 22:21 UTC, wtbarnes commented on changelog/206.removal.rst
> +This is because they are worse versions of the functionality already present in sunpy to reproject images given some model of differential rotation.
This is not necessary.

```suggestion
```

2024-06-24 14:37 UTC, Deus1704 commented
> As noted above, the doc build failure still needs fixing.

Yeah there were few references in the legacy changelog dating back to the initial addition of these functions.

2024-06-24 16:18 UTC, nabobalis commented
Online test is a file download failure.

2024-06-24 16:42 UTC, Deus1704 commented
> Online test is a file download failure.

Yeah, but I believe we should look into it? because the same issue is occurring when I run the online test suite locally and the file being downloaded is a sunpy hosted sample data, so ideally this failure shouldn't occur?

2024-06-24 16:44 UTC, nabobalis commented
> > Online test is a file download failure.
> 
> Yeah, but I believe we should look into it? because the same issue is occurring when I run the online test suite locally and the file being downloaded is a sunpy hosted sample data, so ideally this failure shouldn't occur?

Yeah but it isnt due to this PR so we can gloss over it for this.

2024-06-28 15:57 UTC, merged